server:
  port: 8083

spring:
  application:
    name: company-info
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations:
      - classpath:db
    datasource:
      url: ${datasource.url}
      username: ${datasource.username}
      password: ${datasource.password}
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    template:
      queue: ${rabbitmq.queue.update.message}
      exchange: ${rabbitmq.exchange.update.message}
      routing-key: ${rabbitmq.queue.update.message}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  pathsToMatch: /company/**
  packagesToScan: ru.viktorgezz.company_info
  default-consumes-media-type: application/json
  default-produces-media-type: application/json