server:
  port: 8085

spring:
  application:
    name: api-T-connector
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
    template:
      queue: ${rabbitmq.template.queue}
      exchange: ${rabbitmq.template.exchange}
      routing-key: ${rabbitmq.template.routing.key}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        jdbc.queries: true
    tags:
      application: api-app

token:
  invest-t: ${token_t_invest}
url:
  guide: ${url.guide}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  packagesToScan: ru.viktorgezz.api_T_connector
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
