name: Project Launch

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest changes
        run: git pull origin main

      - name: Stop existing services
        run: |
          cd 
          cd /home/viktorgezz/volume-hub
          docker-compose down || true

      - name: Start services
        run: |
          cd
          cd /home/viktorgezz/volume-hub
          docker-compose up -d --build

      - name: Verify deployment
        run: |
          sleep 240
          docker ps -a